forge 'forge.puppetlabs.com'

mod 'puppetlabs/apt'
mod 'puppetlabs/archive'
mod 'assets', :git => 'git@github.com:frozenfoxx/puppet-assets.git'
mod 'puppetlabs/concat'
mod 'puppetlabs-docker'
mod 'puppet/extlib'
mod 'dhoppe/fail2ban'
mod 'ghoneycutt-hosts'
mod 'puppet/nginx'
mod 'puppetlabs-reboot'
mod 'puppetlabs/stdlib'
mod 'puppetlabs-translate'
mod 'puppet-unattended_upgrades'
